// Front Door Standard: TLS termination, custom domain, caching, WAF rate limiting.
//
// Standard (not Premium) is correct and sufficient: it supports custom WAF rules AND
// rate limiting. Only *managed* rule sets (OWASP CRS) require Premium. Classic tiers are
// retired - AFD (classic) managed certs died 2026-04-14 and classic itself retires
// 2027-03-31 - so Standard/Premium is the only forward option.
//
// TWO RULES IN HERE ARE LOAD-BEARING AND COST REAL MONEY IF REMOVED. See below.

@description('Front Door profile name.')
param profileName string

@description('Endpoint name. NOTE: the resulting hostname is <endpoint>-<hash>.z01.azurefd.net; the hash cannot be predicted.')
param endpointName string

@description('Origin hostname - the Blob static-website host. NOT the VM: MediaMTX cannot be served through a CDN.')
param originHostName string

@description('Origin HTTP port. 80 for the Blob static website; the old MediaMTX topology used 8888.')
param originHttpPort int = 80

@description('Origin HTTPS port. 443 for the Blob static website.')
param originHttpsPort int = 443

@description('Custom domain FQDN, or empty for none.')
param customDomain string = ''

@description('Per-socket-IP request ceiling for the WAF rate-limit rule.')
param wafRateLimitRpm int

@description('Manifest cache TTL, seconds. Short, because playlists change every segment.')
@minValue(1)
@maxValue(59)
param manifestCacheSeconds int = 2

@description('Segment cache TTL, seconds. Segments are immutable once published.')
@minValue(1)
@maxValue(3599)
param segmentCacheSeconds int = 60

// Azure wants d.hh:mm:ss. Built with padLeft rather than string interpolation of the raw
// numbers, which silently produced malformed values like '00:00:12' -> '00:0:12' for any
// value above 9.
var manifestTtl = '00:00:${padLeft(manifestCacheSeconds, 2, '0')}'
var segmentTtl = '00:${padLeft(segmentCacheSeconds / 60, 2, '0')}:${padLeft(segmentCacheSeconds % 60, 2, '0')}'

resource profile 'Microsoft.Cdn/profiles@2024-02-01' = {
  name: profileName
  location: 'global'
  sku: {
    name: 'Standard_AzureFrontDoor'
  }
}

// ---------------------------------------------------------------------------------------
// The hostname hash. autoGeneratedDomainNameLabelScope controls whether the pseudorandom
// hash is REUSED when an endpoint of the same name is deleted and recreated.
//
// TenantReuse is essential here and must never be changed to NoReuse. This service is a
// cold standby that is torn down and redeployed by design; if the hash changed on each
// redeploy, the hostname in every Apple TV's mdm/vlc.xml would break at precisely the
// moment the fallback was being activated.
// ---------------------------------------------------------------------------------------
resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2024-02-01' = {
  parent: profile
  name: endpointName
  location: 'global'
  properties: {
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    enabledState: 'Enabled'
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2024-02-01' = {
  parent: profile
  name: 'relay-origin-group'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 50
    }
    // HEALTH PROBES ARE DELIBERATELY DISABLED.
    //
    // With a single origin there is nothing to fail over TO, so a probe can only ever take
    // the service down - and it did: probing '/' over HTTP against a Blob static website
    // returns 404 (there is no root document) on an account that is HTTPS-only, so Front
    // Door marked the origin unhealthy and answered 404 for every request while the origin
    // itself served /news/index.m3u8 with a 200.
    //
    // Omitting healthProbeSettings disables probing entirely. If a second origin is ever
    // added, reinstate probes with probeProtocol: 'Https' AND a probePath that genuinely
    // returns 200 - note the HLS mirror runs with --delete-destination, so any static
    // health file placed in $web would be deleted on the next sync.
    sessionAffinityState: 'Disabled'
  }
}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2024-02-01' = {
  parent: originGroup
  name: 'relay-vm'
  properties: {
    hostName: originHostName
    httpPort: originHttpPort
    httpsPort: originHttpsPort
    originHostHeader: originHostName
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    // The Blob static website presents a real certificate for *.web.core.windows.net, and
    // the account enforces HTTPS-only, so the origin hop is encrypted and verified. Under
    // the old MediaMTX topology this had to be false (plain HTTP on 8888).
    enforceCertificateNameCheck: true
  }
}

// ---------------------------------------------------------------------------------------
// RULE SET: the two things that cost money if wrong.
// ---------------------------------------------------------------------------------------
resource ruleSet 'Microsoft.Cdn/profiles/ruleSets@2024-02-01' = {
  parent: profile
  name: 'relayCaching'
}

// (1) IGNORE THE `session` QUERY STRING.
//
// MediaMTX appends a per-viewer '?session=<uuid>' to every variant-playlist URL, in
// EVERY hlsVariant (verified on mpegts, fmp4 and lowLatency). With the default cache key
// that makes each viewer unique, the hit rate collapses to ~0, and every client byte also
// costs an origin-egress byte - roughly doubling the bill.
//
// IgnoreSpecifiedQueryStrings is a Standard-tier feature, so no upgrade is needed.
resource manifestRule 'Microsoft.Cdn/profiles/ruleSets/rules@2024-02-01' = {
  parent: ruleSet
  name: 'manifestCaching'
  properties: {
    order: 1
    matchProcessingBehavior: 'Continue'
    conditions: [
      {
        name: 'UrlFileExtension'
        parameters: {
          typeName: 'DeliveryRuleUrlFileExtensionMatchConditionParameters'
          operator: 'Equal'
          matchValues: ['m3u8']
          transforms: ['Lowercase']
        }
      }
    ]
    actions: [
      {
        name: 'RouteConfigurationOverride'
        parameters: {
          typeName: 'DeliveryRuleRouteConfigurationOverrideActionParameters'
          cacheConfiguration: {
            queryStringCachingBehavior: 'IgnoreSpecifiedQueryStrings'
            queryParameters: 'session'
            isCompressionEnabled: 'Disabled'
            // (2) EXPLICIT TTL.
            //
            // MediaMTX emits no Cache-Control. Front Door then assigns a RANDOM 1-3 DAY
            // TTL, which would pin a stale playlist for days - the displays would freeze
            // on old content and look like a streaming failure.
            cacheBehavior: 'OverrideAlways'
            cacheDuration: manifestTtl
          }
        }
      }
    ]
  }
}

// Segments are immutable once written, so they cache for longer. Same session-ignoring
// rationale applies.
resource segmentRule 'Microsoft.Cdn/profiles/ruleSets/rules@2024-02-01' = {
  parent: ruleSet
  name: 'segmentCaching'
  dependsOn: [manifestRule]
  properties: {
    order: 2
    matchProcessingBehavior: 'Stop'
    conditions: [
      {
        name: 'UrlFileExtension'
        parameters: {
          typeName: 'DeliveryRuleUrlFileExtensionMatchConditionParameters'
          operator: 'Equal'
          matchValues: ['ts', 'mp4', 'm4s']
          transforms: ['Lowercase']
        }
      }
    ]
    actions: [
      {
        name: 'RouteConfigurationOverride'
        parameters: {
          typeName: 'DeliveryRuleRouteConfigurationOverrideActionParameters'
          cacheConfiguration: {
            queryStringCachingBehavior: 'IgnoreSpecifiedQueryStrings'
            queryParameters: 'session'
            isCompressionEnabled: 'Disabled'
            cacheBehavior: 'OverrideAlways'
            cacheDuration: segmentTtl
          }
        }
      }
    ]
  }
}

resource route 'Microsoft.Cdn/profiles/afdEndpoints/routes@2024-02-01' = {
  parent: endpoint
  name: 'relay-route'
  dependsOn: [origin, segmentRule]
  properties: {
    originGroup: {
      id: originGroup.id
    }
    ruleSets: [
      {
        id: ruleSet.id
      }
    ]
    supportedProtocols: ['Http', 'Https']
    patternsToMatch: ['/*']
    // HttpsOnly: the storage account sets supportsHttpsTrafficOnly, so an HTTP origin
    // request would be rejected outright.
    forwardingProtocol: 'HttpsOnly'
    linkToDefaultDomain: 'Enabled'
    httpsRedirect: 'Enabled'
    enabledState: 'Enabled'
    cacheConfiguration: {
      queryStringCachingBehavior: 'IgnoreSpecifiedQueryStrings'
      queryParameters: 'session'
      compressionSettings: {
        isCompressionEnabled: false
      }
    }
  }
}

// ---------------------------------------------------------------------------------------
// WAF: rate limiting. Required because HLS is public by default, which makes the egress
// downside unbounded - the ~$423/mo projection assumes 10 Apple TVs and nothing stops a
// scraper multiplying it.
// ---------------------------------------------------------------------------------------
resource wafPolicy 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2024-02-01' = {
  name: replace('${profileName}waf', '-', '')
  location: 'global'
  sku: {
    name: 'Standard_AzureFrontDoor'
  }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      // Prevention, not Detection: a detection-only rate limit would log the abuse while
      // still paying for the egress it was meant to prevent.
      mode: 'Prevention'
    }
    customRules: {
      rules: [
        {
          name: 'rateLimitPerIp'
          priority: 100
          enabledState: 'Enabled'
          ruleType: 'RateLimitRule'
          rateLimitDurationInMinutes: 1
          rateLimitThreshold: wafRateLimitRpm
          matchConditions: [
            {
              matchVariable: 'RequestUri'
              operator: 'Contains'
              negateCondition: false
              matchValue: ['/']
            }
          ]
          action: 'Block'
        }
      ]
    }
  }
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2024-02-01' = {
  parent: profile
  name: 'relay-waf-policy'
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: {
        id: wafPolicy.id
      }
      associations: [
        {
          domains: [
            {
              id: endpoint.id
            }
          ]
          patternsToMatch: ['/*']
        }
      ]
    }
  }
}

// Custom domain. Front Door will not issue a managed certificate until BOTH a
// _dnsauth.<sub> TXT record and the CNAME exist, so this resource sits in
// 'Pending' until DNS is in place - which is why the deploy step polls and is resumable
// across days.
resource domain 'Microsoft.Cdn/profiles/customDomains@2024-02-01' = if (!empty(customDomain)) {
  parent: profile
  name: replace(customDomain, '.', '-')
  properties: {
    hostName: customDomain
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
    }
  }
}

output profileName string = profile.name
// The ONLY authoritative source for the hostname. Everything downstream must read this
// rather than constructing '<endpoint>.azurefd.net', which never resolves.
output endpointHostName string = endpoint.properties.hostName
output endpointId string = endpoint.id
output wafPolicyName string = wafPolicy.name
// Safe-dereferenced: the resource is conditional, and validationProperties is itself
// absent until Azure has generated the token, so a plain access would fail the whole
// deployment on a Phase A (no custom domain) run.
output customDomainValidationToken string = empty(customDomain)
  ? ''
  : (domain!.properties.?validationProperties.?validationToken ?? '')
