#!/usr/bin/env bash
# teardown.sh — remove the relay. COMPLETE BY DEFAULT.
#
#   scripts/teardown.sh                       # complete: delete the resource group -> ~$0/mo
#   scripts/teardown.sh --keep-ip             # keep the static public IP (~$4/mo)
#   scripts/teardown.sh --keep-registry       # keep ACR warm (~$5/mo, no image rebuild)
#   scripts/teardown.sh --keep-ip --keep-registry
#   scripts/teardown.sh --yes                 # skip the typed confirmation (CI)
#   scripts/teardown.sh --dry-run             # show what would be deleted
#
# The default is total removal because the entire cost model rests on this actually
# happening: a fallback that is awkward to switch off quietly becomes a subscription.
#
# WHAT A COMPLETE TEARDOWN CHANGES ON REACTIVATION
#   * the SRT ingest IP will differ (unless --keep-ip)
#   * the SRT passphrase is regenerated, because the Key Vault is purged
#   * the first deploy rebuilds the container image (unless --keep-registry)
# All three mean the page-stream producers need their ingest URLs re-rendered after
# reactivation. That is a config change, not an outage, but it is not zero work.
#
# The Front Door hostname survives regardless: the endpoint pins
# autoGeneratedDomainNameLabelScope to TenantReuse, so the pseudorandom hash is reused even
# after the profile is deleted. Consumer URLs therefore stay valid.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/ui.sh
source "$REPO_ROOT/scripts/lib/ui.sh"

DEPT="${DEPT:-orfe}"
CONFIG_REPO="${CONFIG_REPO:-$REPO_ROOT/../stream-relay-config}"
DEPT_DIR="$CONFIG_REPO/$DEPT"
KEEP_IP=0
KEEP_REGISTRY=0
ASSUME_YES=0
DRY_RUN=0

usage() { sed -n '2,23p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0; }

# ASSUME_YES and DRY_RUN are read by lib/ui.sh's confirm(); shellcheck cannot see through
# the dynamic source path. Scoped to this loop only.
# shellcheck disable=SC2034
while [ $# -gt 0 ]; do
  case "$1" in
    --keep-ip)        KEEP_IP=1 ;;
    --keep-registry)  KEEP_REGISTRY=1 ;;
    --yes|-y)         ASSUME_YES=1 ;;
    --dry-run)        DRY_RUN=1 ;;
    --dept)           DEPT="${2:?}"; DEPT_DIR="$CONFIG_REPO/$DEPT"; shift ;;
    -h|--help)        usage ;;
    # The old flags are gone. Fail with a pointer rather than silently doing something
    # different from what an old runbook expects.
    --soft) die "--soft was removed. Teardown is complete by default now; the closest
    equivalent is: $(basename "$0") --keep-ip --keep-registry" ;;
    --hard) die "--hard was removed - complete teardown is the default. Just run:
    $(basename "$0")" ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

[ -f "$DEPT_DIR/deploy.env" ] || die "missing $DEPT_DIR/deploy.env"
set -a
# shellcheck disable=SC1090
source "$DEPT_DIR/deploy.env"
set +a
# shellcheck source=lib/state.sh
source "$REPO_ROOT/scripts/lib/state.sh"

SELECTIVE=$(( KEEP_IP + KEEP_REGISTRY ))
if [ "$SELECTIVE" -eq 0 ]; then
  banner "STREAM-RELAY TEARDOWN — COMPLETE"
else
  banner "STREAM-RELAY TEARDOWN — COMPLETE, WITH EXCEPTIONS"
fi

az account show >/dev/null 2>&1 || die "not logged in. Run: az login"
if [ "$(az group exists -n "$AZ_RESOURCE_GROUP")" != "true" ]; then
  ok "resource group $AZ_RESOURCE_GROUP does not exist — nothing to tear down"
  exit 0
fi

info "resource group: $AZ_RESOURCE_GROUP"
printf "\n${BOLD}Currently present:${NC}\n"
az resource list -g "$AZ_RESOURCE_GROUP" --query "[].{name:name, type:type}" -o table | sed 's/^/  /'

printf "\n${BOLD}This run will:${NC}\n"
if [ "$SELECTIVE" -eq 0 ]; then
  printf "  ${RED}delete the entire resource group${NC}\n"
  printf "  ${RED}purge the soft-deleted Key Vault${NC} (so the name is immediately reusable)\n"
  printf "  → standby cost afterwards: ${GREEN}~\$0/month${NC}\n"
else
  printf "  delete everything except:\n"
  cost=0
  if [ "$KEEP_IP" = "1" ]; then
    printf "    ${CYAN}·${NC} the static public IP   (~\$4/mo — stable ingest address)\n"
    cost=$(( cost + 4 ))
  fi
  if [ "$KEEP_REGISTRY" = "1" ]; then
    printf "    ${CYAN}·${NC} the container registry (~\$5/mo — no image rebuild)\n"
    cost=$(( cost + 5 ))
  fi
  printf "  → standby cost afterwards: ${YELLOW}~\$%s/month${NC}\n" "$cost"
fi
[ "$KEEP_IP" = "1" ] || printf "  ${YELLOW}the ingest IP will change${NC} — re-render producer URLs on reactivation\n"
printf "  ${YELLOW}the SRT passphrase will be regenerated${NC} — re-render producer URLs\n"

run() {
  if [ "$DRY_RUN" = "1" ]; then printf "    ${DIM}[dry-run] az %s${NC}\n" "$*"; return 0; fi
  az "$@"
}

[ "$DRY_RUN" = "1" ] && { printf "\n"; info "[dry-run] nothing will be deleted"; }

# Destructive and irreversible, so require the resource group name typed out - not a y/n.
if [ "$DRY_RUN" != "1" ] && [ "$ASSUME_YES" != "1" ]; then
  printf "\n${YELLOW}Type the resource group name to confirm deletion: ${NC}"
  read -r typed
  [ "$typed" = "$AZ_RESOURCE_GROUP" ] || die "name did not match — aborted" 0
fi

KV_NAME="${AZ_KEY_VAULT:-}"
KV_LOCATION="${AZ_REGION:-}"

# Key Vault soft-delete cannot be disabled. Without an explicit purge the name stays
# reserved for the retention window and the NEXT deployment fails on a name conflict, which
# would strand a reactivation. Purge protection is deliberately off in keyvault.bicep so
# this is possible.
purge_vault() {
  [ -n "$KV_NAME" ] || return 0
  if az keyvault list-deleted --query "[?name=='$KV_NAME']" -o tsv 2>/dev/null | grep -q .; then
    run keyvault purge --name "$KV_NAME" --location "$KV_LOCATION" \
      && ok "purged $KV_NAME (name immediately reusable)" \
      || warn "could not purge $KV_NAME; a redeploy may hit a name conflict until it expires"
  else
    skipped "$KV_NAME is not in the soft-deleted list"
  fi
}

# ---------------------------------------------------------------------------------------
# Path A: complete. Delete the group, then purge the vault.
# ---------------------------------------------------------------------------------------
if [ "$SELECTIVE" -eq 0 ]; then
  step_header 1 3 "Deleting the resource group"
  run group delete -n "$AZ_RESOURCE_GROUP" --yes
  ok "resource group deleted"

  step_header 2 3 "Purging the soft-deleted Key Vault"
  purge_vault

  step_header 3 3 "Confirming removal"
  if [ "$DRY_RUN" = "1" ]; then
    info "[dry-run] skipping confirmation"
    exit 0
  fi
  if [ "$(az group exists -n "$AZ_RESOURCE_GROUP")" = "true" ]; then
    warn "the resource group still reports as existing; deletion may still be finishing"
    info "check with: az group show -n $AZ_RESOURCE_GROUP"
  else
    ok "nothing remains"
  fi
  # Local state describes resources that no longer exist. Keeping it would make a later
  # --resume skip steps whose resources are gone.
  rm -f "$STATE_FILE" && ok "cleared local deployment state"
  printf "\n"
  ok "standby cost is now approximately \$0/month"
  warn "producer ingest URLs are now stale (new IP and new passphrase on reactivation)"
  info "reactivate with: scripts/bootstrap.sh --with-role-assignments"
  exit 0
fi

# ---------------------------------------------------------------------------------------
# Path B: selective. Delete resource by resource, honouring the --keep-* flags.
# Order matters: Front Door before the VM (nothing should route to a vanishing origin), the
# VM before its NIC, and the NIC before anything touching the subnet.
# ---------------------------------------------------------------------------------------
step_header 1 6 "Front Door and WAF"
if az afd profile show -g "$AZ_RESOURCE_GROUP" --profile-name "$AZ_FRONTDOOR_PROFILE" >/dev/null 2>&1; then
  # NOTE: `az afd profile delete` has no --yes flag; passing it errors.
  run afd profile delete -g "$AZ_RESOURCE_GROUP" --profile-name "$AZ_FRONTDOOR_PROFILE"
  ok "deleted $AZ_FRONTDOOR_PROFILE"
else
  skipped "no Front Door profile"
fi
waf="${AZ_FRONTDOOR_PROFILE//-/}waf"
if az network front-door waf-policy show -g "$AZ_RESOURCE_GROUP" -n "$waf" >/dev/null 2>&1; then
  run network front-door waf-policy delete -g "$AZ_RESOURCE_GROUP" -n "$waf"
  ok "deleted $waf"
else
  skipped "no WAF policy"
fi

step_header 2 6 "Virtual machine"
if az vm show -g "$AZ_RESOURCE_GROUP" -n "$AZ_VM_NAME" >/dev/null 2>&1; then
  run vm delete -g "$AZ_RESOURCE_GROUP" -n "$AZ_VM_NAME" --yes
  ok "deleted $AZ_VM_NAME (OS disk follows: deleteOption=Delete)"
else
  skipped "no VM"
fi
# The NIC must go before any subnet work or Azure returns InUseSubnetCannotBeDeleted.
if az network nic show -g "$AZ_RESOURCE_GROUP" -n "${AZ_VM_NAME}-nic" >/dev/null 2>&1; then
  run network nic delete -g "$AZ_RESOURCE_GROUP" -n "${AZ_VM_NAME}-nic"
  ok "deleted NIC"
fi

step_header 3 6 "Network"
if az network vnet show -g "$AZ_RESOURCE_GROUP" -n relay-vnet >/dev/null 2>&1; then
  run network vnet delete -g "$AZ_RESOURCE_GROUP" -n relay-vnet && ok "deleted relay-vnet" \
    || warn "could not delete relay-vnet"
fi
if az network nsg show -g "$AZ_RESOURCE_GROUP" -n "${AZ_NSG_NAME:-relay-nsg}" >/dev/null 2>&1; then
  run network nsg delete -g "$AZ_RESOURCE_GROUP" -n "${AZ_NSG_NAME:-relay-nsg}" \
    && ok "deleted NSG" || warn "could not delete the NSG"
fi
if [ "$KEEP_IP" = "1" ]; then
  skipped "keeping relay-pip so the ingest address survives reactivation"
elif az network public-ip show -g "$AZ_RESOURCE_GROUP" -n relay-pip >/dev/null 2>&1; then
  run network public-ip delete -g "$AZ_RESOURCE_GROUP" -n relay-pip && ok "deleted relay-pip" \
    || warn "could not delete relay-pip"
fi

step_header 4 6 "Container registry and storage"
if [ "$KEEP_REGISTRY" = "1" ]; then
  skipped "keeping $AZ_ACR_NAME so reactivation needs no image build"
elif az acr show -n "$AZ_ACR_NAME" -g "$AZ_RESOURCE_GROUP" >/dev/null 2>&1; then
  run acr delete -n "$AZ_ACR_NAME" -g "$AZ_RESOURCE_GROUP" --yes && ok "deleted $AZ_ACR_NAME"
else
  skipped "no registry"
fi
if [ -n "${AZ_STORAGE_ACCOUNT:-}" ] \
  && az storage account show -n "$AZ_STORAGE_ACCOUNT" -g "$AZ_RESOURCE_GROUP" >/dev/null 2>&1; then
  run storage account delete -n "$AZ_STORAGE_ACCOUNT" -g "$AZ_RESOURCE_GROUP" --yes \
    && ok "deleted $AZ_STORAGE_ACCOUNT (HLS delivery origin)"
fi

step_header 5 6 "Key Vault and identities"
if [ -n "$KV_NAME" ] && az keyvault show -n "$KV_NAME" -g "$AZ_RESOURCE_GROUP" >/dev/null 2>&1; then
  run keyvault delete -n "$KV_NAME" -g "$AZ_RESOURCE_GROUP" && ok "deleted $KV_NAME"
  [ "$DRY_RUN" = "1" ] || purge_vault
fi
for ident in "${AZ_IDENTITY_CI:-}" "${AZ_IDENTITY_VM:-}"; do
  [ -n "$ident" ] || continue
  if az identity show -g "$AZ_RESOURCE_GROUP" -n "$ident" >/dev/null 2>&1; then
    run identity delete -g "$AZ_RESOURCE_GROUP" -n "$ident" && ok "deleted $ident"
  fi
done

step_header 6 6 "Confirming"
printf "\n${BOLD}Remaining:${NC}\n"
az resource list -g "$AZ_RESOURCE_GROUP" --query "[].{name:name, type:type}" -o table | sed 's/^/  /'

if [ "$DRY_RUN" = "1" ]; then
  printf "\n"; info "[dry-run] nothing was deleted"; exit 0
fi

# Report anything hourly-billable that survived. An orphaned disk or VM is a silent monthly
# charge, and this is exactly where it would hide.
query="[?type=='Microsoft.Compute/disks' || type=='Microsoft.Compute/virtualMachines' || type=='Microsoft.Network/networkInterfaces'"
[ "$KEEP_IP" = "1" ]       || query="$query || type=='Microsoft.Network/publicIPAddresses'"
[ "$KEEP_REGISTRY" = "1" ] || query="$query || type=='Microsoft.ContainerRegistry/registries'"
query="$query].name"
unexpected=$(az resource list -g "$AZ_RESOURCE_GROUP" --query "$query" -o tsv)
printf "\n"
if [ -n "$unexpected" ]; then
  warn "these should have been removed and are still billable:"
  while IFS= read -r r; do warn "  $r"; done <<< "$unexpected"
  exit 1
fi
ok "no unexpected billable resources remain"
if [ "$KEEP_IP" = "1" ]; then
  info "ingest IP retained — producer URLs keep working"
else
  warn "ingest IP released — re-render producer URLs after reactivation"
fi
warn "SRT passphrase was purged with the vault — it is regenerated on the next deploy"
info "reactivate with: scripts/bootstrap.sh --with-role-assignments"
