#!/usr/bin/env bash
# teardown.sh — remove the relay's own resources. Never the host it runs on.
#
#   scripts/teardown.sh --keep-ip --keep-registry   # the normal call
#   scripts/teardown.sh --dry-run                   # show what would be removed
#   scripts/teardown.sh --yes                       # skip the typed confirmation (CI)
#
# Removes: the SRT ingest NSG rule, the budget, the CI identity, and the relay container
# on the VM. Leaves everything else, because everything else is adopted — the VM, its NIC,
# vnet, subnet, NSG, static public IP, Key Vault, disks and alert rules all existed before
# this project and belong to the host. The :443 and :80 rules stay too: VDO.Ninja serves on
# one and certbot renews over the other.
#
# A complete teardown (deleting the resource group) is REFUSED when
# SHARED_RESOURCE_GROUP is not exactly "false", and fails closed if the flag is absent.
#
# WHAT A COMPLETE TEARDOWN CHANGES ON REACTIVATION
#   * the SRT ingest IP will differ (unless --keep-ip)
#   * the SRT passphrase is regenerated, because the Key Vault is purged
#   * the first deploy rebuilds the container image (unless --keep-registry)
# All three mean the page-stream producers need their ingest URLs re-rendered after
# reactivation. That is a config change, not an outage, but it is not zero work.
#
# The Front Door hostname survives regardless: the endpoint pins
# autoGeneratedDomainNameLabelScope to TenantReuse, so the pseudorandom hash is reused even
# after the profile is deleted. Consumer URLs therefore stay valid.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/ui.sh
source "$REPO_ROOT/scripts/lib/ui.sh"

DEPT="${DEPT:-orfe}"
CONFIG_REPO="${CONFIG_REPO:-$REPO_ROOT/../stream-relay-config}"
DEPT_DIR="$CONFIG_REPO/$DEPT"
KEEP_IP=0
KEEP_REGISTRY=0
ASSUME_YES=0
DRY_RUN=0

usage() { sed -n '2,23p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0; }

# ASSUME_YES and DRY_RUN are read by lib/ui.sh's confirm(); shellcheck cannot see through
# the dynamic source path. Scoped to this loop only.
# shellcheck disable=SC2034
while [ $# -gt 0 ]; do
  case "$1" in
    --keep-ip)        KEEP_IP=1 ;;
    --keep-registry)  KEEP_REGISTRY=1 ;;
    --yes|-y)         ASSUME_YES=1 ;;
    --dry-run)        DRY_RUN=1 ;;
    --dept)           DEPT="${2:?}"; DEPT_DIR="$CONFIG_REPO/$DEPT"; shift ;;
    -h|--help)        usage ;;
    # The old flags are gone. Fail with a pointer rather than silently doing something
    # different from what an old runbook expects.
    --soft) die "--soft was removed. Teardown is complete by default now; the closest
    equivalent is: $(basename "$0") --keep-ip --keep-registry" ;;
    --hard) die "--hard was removed - complete teardown is the default. Just run:
    $(basename "$0")" ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

[ -f "$DEPT_DIR/deploy.env" ] || die "missing $DEPT_DIR/deploy.env"
set -a
# shellcheck disable=SC1090
source "$DEPT_DIR/deploy.env"
set +a
# shellcheck source=lib/state.sh
source "$REPO_ROOT/scripts/lib/state.sh"

SELECTIVE=$(( KEEP_IP + KEEP_REGISTRY ))

# ---------------------------------------------------------------------------------------
# HARD GUARD: a shared resource group must never be deleted.
#
# orfe-dept-azure-rg is not dedicated to the relay. It holds orfe-web-vm, that VM's Key
# Vault, its vnet, disks, disk-encryption set, Log Analytics workspace and alert rules -
# none of which this project created. Deleting the group, or purging a vault the relay does
# not own, destroys all of it.
#
# Fails CLOSED: an unset flag is treated as shared. A teardown that refuses too often costs
# a manual cleanup; one that deletes too much costs a VM somebody parked for a reason.
# ---------------------------------------------------------------------------------------
if [ "${SHARED_RESOURCE_GROUP:-true}" != "false" ] && [ "$SELECTIVE" -eq 0 ]; then
  die "refusing to delete $AZ_RESOURCE_GROUP: SHARED_RESOURCE_GROUP is not false.

  That group holds resources this project did not create. Complete teardown would take
  them with it.

  Use --selective, which removes only the relay's own resources by name." 2
fi

if [ "$SELECTIVE" -eq 0 ]; then
  banner "STREAM-RELAY TEARDOWN — COMPLETE"
else
  banner "STREAM-RELAY TEARDOWN — COMPLETE, WITH EXCEPTIONS"
fi

az account show >/dev/null 2>&1 || die "not logged in. Run: az login"
if [ "$(az group exists -n "$AZ_RESOURCE_GROUP")" != "true" ]; then
  ok "resource group $AZ_RESOURCE_GROUP does not exist — nothing to tear down"
  exit 0
fi

info "resource group: $AZ_RESOURCE_GROUP"
printf "\n${BOLD}Currently present:${NC}\n"
az resource list -g "$AZ_RESOURCE_GROUP" --query "[].{name:name, type:type}" -o table | sed 's/^/  /'

printf "\n${BOLD}This run will:${NC}\n"
if [ "$SELECTIVE" -eq 0 ]; then
  printf "  ${RED}delete the entire resource group${NC}\n"
  printf "  ${RED}purge the soft-deleted Key Vault${NC} (so the name is immediately reusable)\n"
  printf "  → standby cost afterwards: ${GREEN}~\$0/month${NC}\n"
else
  printf "  delete everything except:\n"
  cost=0
  if [ "$KEEP_IP" = "1" ]; then
    printf "    ${CYAN}·${NC} the static public IP   (~\$4/mo — stable ingest address)\n"
    cost=$(( cost + 4 ))
  fi
  if [ "$KEEP_REGISTRY" = "1" ]; then
    printf "    ${CYAN}·${NC} the container registry (~\$5/mo — no image rebuild)\n"
    cost=$(( cost + 5 ))
  fi
  printf "  → standby cost afterwards: ${YELLOW}~\$%s/month${NC}\n" "$cost"
fi
[ "$KEEP_IP" = "1" ] || printf "  ${YELLOW}the ingest IP will change${NC} — re-render producer URLs on reactivation\n"
printf "  ${YELLOW}the SRT passphrase will be regenerated${NC} — re-render producer URLs\n"

run() {
  if [ "$DRY_RUN" = "1" ]; then printf "    ${DIM}[dry-run] az %s${NC}\n" "$*"; return 0; fi
  az "$@"
}

[ "$DRY_RUN" = "1" ] && { printf "\n"; info "[dry-run] nothing will be deleted"; }

# Destructive and irreversible, so require the resource group name typed out - not a y/n.
if [ "$DRY_RUN" != "1" ] && [ "$ASSUME_YES" != "1" ]; then
  printf "\n${YELLOW}Type the resource group name to confirm deletion: ${NC}"
  read -r typed
  [ "$typed" = "$AZ_RESOURCE_GROUP" ] || die "name did not match — aborted" 0
fi

KV_NAME="${AZ_KEY_VAULT:-}"
KV_LOCATION="${AZ_REGION:-}"

# Key Vault soft-delete cannot be disabled. Without an explicit purge the name stays
# reserved for the retention window and the NEXT deployment fails on a name conflict, which
# would strand a reactivation. Purge protection is deliberately off in keyvault.bicep so
# this is possible.
purge_vault() {
  # RELAY_OWNS_KEY_VAULT=false means this vault was created with the VM and is reused. A
  # purge would destroy secrets belonging to something else and cannot be undone.
  if [ "${RELAY_OWNS_KEY_VAULT:-false}" != "true" ]; then
    skipped "$KV_NAME is not owned by the relay - not purging"
    return 0
  fi
  [ -n "$KV_NAME" ] || return 0
  if az keyvault list-deleted --query "[?name=='$KV_NAME']" -o tsv 2>/dev/null | grep -q .; then
    run keyvault purge --name "$KV_NAME" --location "$KV_LOCATION" \
      && ok "purged $KV_NAME (name immediately reusable)" \
      || warn "could not purge $KV_NAME; a redeploy may hit a name conflict until it expires"
  else
    skipped "$KV_NAME is not in the soft-deleted list"
  fi
}

# ---------------------------------------------------------------------------------------
# Path A: complete. Delete the group, then purge the vault.
#
# Only reachable when the group is dedicated to the relay (SHARED_RESOURCE_GROUP=false).
# ---------------------------------------------------------------------------------------
if [ "$SELECTIVE" -eq 0 ]; then
  step_header 1 3 "Deleting the resource group"
  run group delete -n "$AZ_RESOURCE_GROUP" --yes
  ok "resource group deleted"

  step_header 2 3 "Purging the soft-deleted Key Vault"
  purge_vault

  step_header 3 3 "Confirming removal"
  if [ "$DRY_RUN" = "1" ]; then
    info "[dry-run] skipping confirmation"
    exit 0
  fi
  if [ "$(az group exists -n "$AZ_RESOURCE_GROUP")" = "true" ]; then
    warn "the resource group still reports as existing; deletion may still be finishing"
    info "check with: az group show -n $AZ_RESOURCE_GROUP"
  else
    ok "nothing remains"
  fi
  # Local state describes resources that no longer exist. Keeping it would make a later
  # --resume skip steps whose resources are gone.
  rm -f "$STATE_FILE" && ok "cleared local deployment state"
  printf "\n"
  ok "standby cost is now approximately \$0/month"
  warn "producer ingest URLs are now stale (new IP and new passphrase on reactivation)"
  info "reactivate with: scripts/bootstrap.sh --with-role-assignments"
  exit 0
fi

# ---------------------------------------------------------------------------------------
# Path B: selective — the only path that runs against a shared, adopted deployment.
#
# THIS DELETES ONLY WHAT THE RELAY CREATED.
#
# Everything the relay runs on was already here and is adopted: the VM, its NIC, vnet,
# subnet, NSG, static public IP, Key Vault, disks, disk-encryption set, Log Analytics
# workspace and alert rules. An earlier version of this path deleted all of those, which
# was correct when the deployment created them and would now destroy orfe-web-vm, its
# certificate lineage and the VDO.Ninja install beside it.
#
# It also leaves the :443 and :80 NSG rules alone. They predate the relay in spirit - the
# VM served HTTPS before - and VDO.Ninja at /meet/ still needs both, the second for ACME.
# Only the SRT ingest rule is the relay's own.
# ---------------------------------------------------------------------------------------
step_header 1 5 "Relay containers on the VM"
if [ "$DRY_RUN" = "1" ]; then
  skipped "[dry-run] would stop and remove the mediamtx container"
else
  if az vm run-command invoke -g "$AZ_RESOURCE_GROUP" -n "$AZ_VM_NAME" \
       --command-id RunShellScript --scripts 'docker rm -f stream-relay >/dev/null 2>&1 || true; echo stopped' \
       >/dev/null 2>&1; then
    ok "stopped the relay container (nginx and certbot left running for /meet/)"
  else
    warn "could not reach the VM to stop the relay container"
  fi
fi

step_header 2 5 "SRT ingest rule"
if az network nsg rule show -g "$AZ_RESOURCE_GROUP" --nsg-name "${AZ_NSG_NAME:-${AZ_VM_NAME}-nsg}" \
     -n AllowSrtIngest >/dev/null 2>&1; then
  run network nsg rule delete -g "$AZ_RESOURCE_GROUP" \
    --nsg-name "${AZ_NSG_NAME:-${AZ_VM_NAME}-nsg}" -n AllowSrtIngest \
    && ok "removed AllowSrtIngest (443 and 80 retained: VDO.Ninja and ACME need them)"
else
  skipped "no SRT ingest rule"
fi

step_header 3 5 "Budget"
if az consumption budget show --budget-name relay-budget >/dev/null 2>&1; then
  run consumption budget delete --budget-name relay-budget && ok "deleted the budget"
else
  skipped "no budget"
fi

step_header 4 5 "CI identity"
# The VM's identity is SystemAssigned and belongs to the VM, so it is never touched here.
if [ -n "${AZ_IDENTITY_CI:-}" ] \
   && az identity show -g "$AZ_RESOURCE_GROUP" -n "$AZ_IDENTITY_CI" >/dev/null 2>&1; then
  run identity delete -g "$AZ_RESOURCE_GROUP" -n "$AZ_IDENTITY_CI" \
    && ok "deleted $AZ_IDENTITY_CI (federated credentials go with it)"
else
  skipped "no CI identity"
fi

step_header 5 5 "Confirming what remains"
printf "\n${BOLD}Still present (adopted, deliberately untouched):${NC}\n"
az resource list -g "$AZ_RESOURCE_GROUP" --query "[].{name:name, type:type}" -o table | sed 's/^/  /'

if [ "$DRY_RUN" = "1" ]; then
  printf "\n"; info "[dry-run] nothing was deleted"; exit 0
fi

printf "\n"
ok "relay resources removed; the adopted VM and its services are untouched"
info "the SRT passphrase remains in $KV_NAME - the relay reuses it on the next deploy"
info "reactivate with: scripts/deploy.sh"
